export const mainTypes = {
    GET_GREETING: 'GET_GREETING',
    GET_PHOTO_GALLERY: 'GET_PHOTO_GALLERY',
    GET_ABOUT: 'GET_ABOUT',
    GET_DESTINATIONS: 'GET_DESTINATIONS',
    GET_VIDEOS: 'GET_VIDEOS',
    GET_HELPERS: 'ADD_HELPERS',
    GET_COUNTRIES_FOR_SELECT: 'GET_COUNTRIES_FOR_SELECT',

    //работа со компонентом Form
    ADD_VIDEO_INPUT: 'ADD_VIDEO_INPUT',
    ADD_VIDEO_RECORDS_INPUT: 'ADD_VIDEO_RECORDS_INPUT',
    ADD_EMPTY_VIDEO_BLOCK: 'ADD_EMPTY_VIDEO_BLOCK',
    DELETE_VIDEO_RECORD: 'DELETE_VIDEO_RECORD',

    //работа со страницей Video
    ADD_VIDEO_CARD: 'ADD_VIDEO_CARD',
    DElETE_VIDEO_CARD: 'DElETE_VIDEO_CARD',
};
