export const mainTypes = {
    GET_GREETING: 'GET_GREETING',
    GET_PHOTO_GALLERY: 'GET_PHOTO_GALLERY',
    GET_ABOUT: 'GET_ABOUT',
    GET_DESTINATIONS: 'GET_DESTINATIONS',
    GET_VIDEOS: 'GET_VIDEOS',
    GET_HELPERS: 'ADD_HELPERS',
    GET_COUNTRIES_FOR_SELECT: 'GET_COUNTRIES_FOR_SELECT',
    ADD_VIDEO_CARD: 'ADD_VIDEO_CARD',
    DELETE_VIDEO_RECORD: 'DELETE_VIDEO_RECORD',
    ADD_VIDEO_RECORD: 'ADD_VIDEO_RECORD',
    DELETE_VIDEO_CARD: 'DELETE_VIDEO_CARD'
};
