export const mainTypes = {
    ADD_GREETING: 'ADD_GREETING',
    ADD_PHOTO_GALLERY: 'ADD_PHOTO_GALLERY',
    ADD_ABOUT: 'ADD_ABOUT',
    ADD_DESTINATIONS: 'ADD_DESTINATIONS',
    ADD_VIDEOS: 'ADD_VIDEOS',
    ADD_HELPERS: 'ADD_HELPERS'
};
